curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_AMS-Regular.ttf > KaTeX_AMS-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_AMS-Regular.woff > KaTeX_AMS-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_AMS-Regular.woff2 > KaTeX_AMS-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Bold.ttf > KaTeX_Caligraphic-Bold.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Bold.woff > KaTeX_Caligraphic-Bold.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Bold.woff2 > KaTeX_Caligraphic-Bold.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Regular.ttf > KaTeX_Caligraphic-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Regular.woff > KaTeX_Caligraphic-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Caligraphic-Regular.woff2 > KaTeX_Caligraphic-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Bold.ttf > KaTeX_Fraktur-Bold.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Bold.woff > KaTeX_Fraktur-Bold.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Bold.woff2 > KaTeX_Fraktur-Bold.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Regular.ttf > KaTeX_Fraktur-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Regular.woff > KaTeX_Fraktur-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Fraktur-Regular.woff2 > KaTeX_Fraktur-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Bold.ttf > KaTeX_Main-Bold.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Bold.woff > KaTeX_Main-Bold.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Bold.woff2 > KaTeX_Main-Bold.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-BoldItalic.ttf > KaTeX_Main-BoldItalic.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-BoldItalic.woff > KaTeX_Main-BoldItalic.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-BoldItalic.woff2 > KaTeX_Main-BoldItalic.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Italic.ttf > KaTeX_Main-Italic.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Italic.woff > KaTeX_Main-Italic.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Italic.woff2 > KaTeX_Main-Italic.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Regular.ttf > KaTeX_Main-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Regular.woff > KaTeX_Main-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Main-Regular.woff2 > KaTeX_Main-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-BoldItalic.ttf > KaTeX_Math-BoldItalic.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-BoldItalic.woff > KaTeX_Math-BoldItalic.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-BoldItalic.woff2 > KaTeX_Math-BoldItalic.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-Italic.ttf > KaTeX_Math-Italic.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-Italic.woff > KaTeX_Math-Italic.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Math-Italic.woff2 > KaTeX_Math-Italic.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Bold.ttf > KaTeX_SansSerif-Bold.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Bold.woff > KaTeX_SansSerif-Bold.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Bold.woff2 > KaTeX_SansSerif-Bold.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Italic.ttf > KaTeX_SansSerif-Italic.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Italic.woff > KaTeX_SansSerif-Italic.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Italic.woff2 > KaTeX_SansSerif-Italic.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Regular.ttf > KaTeX_SansSerif-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Regular.woff > KaTeX_SansSerif-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_SansSerif-Regular.woff2 > KaTeX_SansSerif-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Script-Regular.ttf > KaTeX_Script-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Script-Regular.woff > KaTeX_Script-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Script-Regular.woff2 > KaTeX_Script-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size1-Regular.ttf > KaTeX_Size1-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size1-Regular.woff > KaTeX_Size1-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size1-Regular.woff2 > KaTeX_Size1-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size2-Regular.ttf > KaTeX_Size2-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size2-Regular.woff > KaTeX_Size2-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size2-Regular.woff2 > KaTeX_Size2-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size3-Regular.ttf > KaTeX_Size3-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size3-Regular.woff > KaTeX_Size3-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size3-Regular.woff2 > KaTeX_Size3-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size4-Regular.ttf > KaTeX_Size4-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size4-Regular.woff > KaTeX_Size4-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Size4-Regular.woff2 > KaTeX_Size4-Regular.woff2
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Typewriter-Regular.ttf > KaTeX_Typewriter-Regular.ttf
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Typewriter-Regular.woff > KaTeX_Typewriter-Regular.woff
curl  https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/fonts/KaTeX_Typewriter-Regular.woff2 > KaTeX_Typewriter-Regular.woff2
