jupyter nbconvert tokyo.ipynb --to python
jupyter nbconvert mhlw.ipynb --to python
jupyter nbconvert prefectures.ipynb --to python
jupyter nbconvert heatmap.ipynb --to python
jupyter nbconvert hokkaido.ipynb --to python
jupyter nbconvert maps.ipynb --to python
jupyter nbconvert airregist.ipynb --to python
jupyter nbconvert vh-contours.ipynb --to python
jupyter nbconvert nhk.ipynb --to python
jupyter nbconvert np00023.ipynb --to python
jupyter nbconvert pcr-lr.ipynb --to python
